# Generated by Django 2.1.7 on 2019-12-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20191201_1355'),
        ('contest', '0010_auto_20190326_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='groups',
            field=models.ManyToManyField(to='account.Group'),
        ),
    ]
