# Generated by Django 2.1.7 on 2019-12-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0014_problem_share_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='forbid_keyword',
            field=models.TextField(blank=True, default=''),
        ),
    ]
